language: elixir

cache:
  - apt
  - directories:
      - ~/.mongodb

elixir:
  - 1.3
  - 1.4
  - 1.5

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGOVERSION}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGOVERSION}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGOVERSION}/bin/mongod --version
  - mkdir db

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - (cd examples/simple; mix deps.get)

before_script:
  - ${PWD}/mongodb-linux-x86_64-${MONGOVERSION}/bin/mongod --dbpath db --logpath mongodb.log --fork

script:
  - mix test
  - (cd examples/simple; mix test)

after_script:
  - mix deps.get --only docs
  - mix inch.report
  - MIX_ENV=test mix coveralls.travis

env:
  matrix:
    - MONGOVERSION=2.4.14
    - MONGOVERSION=2.6.12
    - MONGOVERSION=3.0.12
    - MONGOVERSION=3.2.10
